
# My Archlinux System 

# Make Sure time is currect
timedatectl set-ntp true

genfstab -U /mnt > /mnt/etc/fstab


# Install System

pacstrap /mnt base linux linux-firmware zsh wget curl axel htop tree ntfs-3g exfat-utils zip unzip rar unrar p7zip tcpdump nmap

pacstrap /mnt zsh zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-lovers zsh-syntax-highlighting

pacstrap /mnt thunderbird thunderbird-i18n-en-us thunderbird-i18n-zh-cn


# editors
pacstrap /mnt vim nano texlive-core texlive-langchinese

# man
pacstrap /mnt man-db man-pages texinfo

# nettools
pacstrap /mnt iproute2 

# devel language
pacstrap /mnt go python python-pip nodejs npm rust gcc gdb 

# devel tools
pacstrap /mnt ctags tmux make cmake git docker docker-compose kubectl vscode firefox gdb-dashboard clang llvm privoxy

# Xorg
pacstrap /mnt nvidia opencl-nvidia rrdtool opengl-man-pages mesa-vdpau libva-mesa-driver cuda cudnn tensorflow-opt-cuda python-tensorflow-opt-cuda tensorboard xorg xorg-xinit xorg-xrandr xorg-twm xterm
cat > /mnt/etc/X11/xorg.conf << EOF
# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 390.48  (buildmeister@swio-display-x86-rhel47-07)  Thu Mar 22 01:07:32 PDT 2018

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName	   "TCL"
    Modeline       "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
    Option   	   "PreferredMode" "1920x1080_60.00"
EndSection

Section "Monitor"
    Identifier     "Monitor1"
    VendorName	   "DELL"
    Modeline       "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
    #Modeline 	   "1080x1920_60.00"  176.50  1080 1168 1280 1480  1920 1923 1933 1989 -hsync +vsync
    Option   	   "PreferredMode" "1920x1080_60.00"
    Option	   "RightOf" "Monitor0"
EndSection

Section "Device"
    Identifier     "GTX1060"
    Driver         "nvidia"
    BusID	   "PCI:01:00:0"
    VendorName     "NVIDIA Corporation"
    Option	   "Monitor-HDMI-0" "Monitor0"
    Option	   "Monitor-DisplayPort-0" "Monitor1"
    Option 	   "Coolbits" "4"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "GTX1060"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
	Modes	   "1920x1080_60.00"
    EndSubSection
EndSection

Section "Screen"
    Identifier	   "Screen1"
    Device	   "GTX1060"
    Monitor	   "Monitor1"
    DefaultDepth   24
    SubSection	   "Display"
	Depth	   24
	Modes	   "1920x1080_60.00"
    EndSubSection
EndSection
EOF

# GUI
pacstrap /mnt gdm gnome gnome-extra qt5 fcitx fcitx-configtool fcitx-qt4 fcitx-qt5 fcitx-gtk2 fcitx-gtk3 fcitx-sogoupinyin powerline powerline-fonts wqy-zenhei wqy-microhei wqy-bitmapfont tor


arch-chroot /mnt

systemctl enable gdm


ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

hwclock --systohc

locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf


echo "PC" > /etc/hostname
